global:
  scrape_interval: 5s 
  external_labels:
    monitor: "monitor"
scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
  - job_name: "nginx-exporter"
    static_configs:
      - targets: ["nginx-prometheus-exporter:9113"]
  - job_name: node-exporter
    static_configs:
      - targets: ["node-exporter:9100"]
  - job_name: docker-metrics
    static_configs:
      - targets: ["localhost:9323"]