global:
  scrape_interval: 5s 
  external_labels:
    monitor: "monitor"
scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
  - job_name: "nginx-exporter"
    static_configs:
      - targets: ["nginx-prometheus-exporter:9113"]
  - job_name: node-exporter
    static_configs:
    # TO-DO change for safe
      - targets: ["node-exporter:9100"]
  - job_name: docker-metrics
    static_configs:
    # docker ip address -> ip addr docker0
      - targets: ["host.docker.internal:9323"]
  - job_name: cadvisor-metrics
    static_configs:
      - targets: ["cadvisor:8088"]