blank_issues_enabled: true
contact_links:
  - name: Get help from the community on Discord
    url: https://discord.gg/MjjfP5qpYt
    about: Join the Fingerstyle Taiwan Discord for community-powered support!
