name: "💡 Feature Request"
description: Create a new issue for new feature requests
title: "💡 [REQUEST] - <Title>"
labels: [
   "question"
]
body:
   - type: textarea
     id: summary
     attributes:
       label: "Summary"
       description: Provides a brief description of the feature.
       placeholder: Describe your feature request in a few lines
     validations:
       required: true
   - type: textarea
     id: basic_example
     attributes:
       label: "Basic Example"
       description: Describe some basic examples of your functionality here. .
       placeholder: An introduction to your function.
     validations:
       required: true