# Generated by Django 4.0.7 on 2022-10-03 16:00

import core.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to=core.models.avatar_image_file_path)),
                ('birthdate', models.DateField(blank=True, null=True)),
                ('country', django_countries.fields.CountryField(default='TW', max_length=2)),
                ('guitar_brand', models.CharField(blank=True, max_length=20, null=True)),
                ('guitar_model', models.CharField(blank=True, max_length=20, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
