# Generated by Django 4.0.7 on 2022-10-04 02:39

import ckeditor.fields
import core.models
from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_profile_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.avatar_image_file_path, verbose_name='頭貼'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='簡介'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='birthdate',
            field=models.DateField(blank=True, null=True, verbose_name='生日'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='country',
            field=django_countries.fields.CountryField(default='TW', max_length=2, verbose_name='國家/地區'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('MALE', '男生'), ('FEMALE', '女生'), ('OTHER', '其他')], default='OTHER', max_length=6, verbose_name='性別'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='guitar_brand',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='吉他品牌'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='guitar_model',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='吉他型號'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=255, unique=True, verbose_name='信箱'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=255, verbose_name='暱稱'),
        ),
    ]
