# Generated by Django 4.0.8 on 2022-10-27 03:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_contestlikes_contest_likes_profile_liked_contest_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='liked_contest',
        ),
        migrations.AddField(
            model_name='contestlikes',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contest',
            name='likes',
            field=models.ManyToManyField(through='core.ContestLikes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='contestlikes',
            unique_together={('user', 'contest')},
        ),
        migrations.RemoveField(
            model_name='contestlikes',
            name='profile',
        ),
    ]
