# Generated by Django 4.0.8 on 2022-10-06 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_user_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
