# Generated by Django 4.0.8 on 2022-10-27 03:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_remove_profile_liked_contest_contestlikes_user_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contestlikes",
            name="contest",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.contest",
            ),
        ),
        migrations.AlterField(
            model_name="contestlikes",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
