# Generated by Django 4.0.8 on 2022-10-06 06:08

import ckeditor.fields
import core.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_delete_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to=core.models.avatar_image_file_path, verbose_name='頭貼')),
                ('gender', models.CharField(choices=[('MALE', '男生'), ('FEMALE', '女生'), ('OTHER', '其他')], default='OTHER', max_length=6, verbose_name='性別')),
                ('bio', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='簡介')),
                ('birthdate', models.DateField(blank=True, null=True, verbose_name='生日')),
                ('country', django_countries.fields.CountryField(default='TW', max_length=2, verbose_name='國家/地區')),
                ('guitar_brand', models.CharField(blank=True, max_length=20, null=True, verbose_name='吉他品牌')),
                ('guitar_model', models.CharField(blank=True, max_length=20, null=True, verbose_name='吉他型號')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
