# Generated by Django 4.0.8 on 2022-10-10 16:14

import ckeditor.fields
import core.models
from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='名字')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to=core.models.artist_image_file_path, verbose_name='頭貼')),
                ('cover', models.ImageField(blank=True, null=True, upload_to=core.models.artist_image_file_path, verbose_name='封面照片')),
                ('country', django_countries.fields.CountryField(default='TW', max_length=2, verbose_name='國家/地區')),
                ('information', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='簡介')),
                ('website', models.URLField(blank=True, verbose_name='個人網站')),
                ('fb_link', models.URLField(blank=True, verbose_name='Facebook')),
                ('ig_link', models.URLField(blank=True, verbose_name='Instagram')),
                ('yt_link', models.URLField(blank=True, verbose_name='Youtube')),
            ],
        ),
    ]
