# Generated by Django 4.0.8 on 2022-10-13 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_artist'),
        ('core', '0009_contest'),
    ]

    operations = [
    ]
