# Generated by Django 4.0.8 on 2022-10-30 14:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0010_alter_contest_identity_restrictions"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contest",
            options={
                "get_latest_by": "id",
                "ordering": ["id"],
                "verbose_name": "比賽",
                "verbose_name_plural": "比賽",
            },
        ),
    ]
