# Generated by Django 4.0.8 on 2022-10-30 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_alter_contest_identity_restrictions"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="artist",
            options={
                "get_latest_by": "id",
                "ordering": ["id"],
                "verbose_name": "指彈家",
                "verbose_name_plural": "指彈家",
            },
        ),
    ]
