# Generated by Django 4.0.8 on 2022-12-12 12:45

import ckeditor.fields
import django.db.models.deletion
import django_countries.fields
import taggit.managers
from django.conf import settings
from django.db import migrations, models

import core.models


class Migration(migrations.Migration):

    dependencies = [
        ("taggit", "0005_auto_20220424_2025"),
        ("core", "0016_comments"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comments",
            name="content",
            field=ckeditor.fields.RichTextField(verbose_name="留言內容"),
        ),
        migrations.AlterField(
            model_name="comments",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="contest",
            name="email",
            field=models.EmailField(blank=True, max_length=255, verbose_name="聯絡信箱"),
        ),
        migrations.AlterField(
            model_name="contest",
            name="identity_restrictions",
            field=core.models.ChoiceArrayField(
                base_field=models.CharField(
                    choices=[
                        ("junior", "高中組"),
                        ("personal", "個人組"),
                        ("team", "團體組"),
                        ("fingerstyle", "演奏組"),
                        ("society", "社會組"),
                    ],
                    default="personal",
                    max_length=12,
                ),
                blank=True,
                null=True,
                size=None,
                verbose_name="身份限制",
            ),
        ),
        migrations.AlterField(
            model_name="contest",
            name="regional_restrictions",
            field=django_countries.fields.CountryField(
                blank=True, default="TW", max_length=2, verbose_name="國家/地區限制"
            ),
        ),
        migrations.AlterField(
            model_name="contest",
            name="tags",
            field=taggit.managers.TaggableManager(
                blank=True,
                help_text="A comma-separated list of tags.",
                through="taggit.TaggedItem",
                to="taggit.Tag",
                verbose_name="Tags",
            ),
        ),
    ]
