---
name: Checks
on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches: '**'
jobs:
  test-lint:
    name: Test and Lint
    runs-on: ubuntu-20.04
    if: "!contains(github.event.commits[0].message, '[skip ci]')"

    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test
        run: docker-compose run --rm django-app sh -c "python manage.py wait_for_db && python manage.py test"
      - name: Lint
        run: docker-compose run --rm django-app sh -c "flake8"